# Contact the folks in #dev-ci for this one, it looks like it
# is a partial copy of the CI checks from ClickHouse/ClickHouse

---
name: PullRequestCI

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches-ignore:
      - 'new-nav'

jobs:
  DocsCheck:
    runs-on: [self-hosted, func-tester-aarch64]
    steps:
      - name: Set envs
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/docs_check
          REPO_COPY=${{runner.temp}}/docs_check/ClickHouse
          EOF
      - name: Clear repository
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
          sudo rm -rf "$TEMP_PATH" && mkdir -p "$TEMP_PATH"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: "ClickHouse/ClickHouse"
          path: "ClickHouse"
          ref: "master"
      - name: Docs Check
        run: |
          cp -r "$GITHUB_WORKSPACE/ClickHouse" "$TEMP_PATH"
          cd "$REPO_COPY/tests/ci"
          python3 docs_check.py --force --docs-branch "$GITHUB_REF"
          python3 finish_check.py
      - name: Cleanup
        if: always()
        run: |
          docker kill "$(docker ps -q)" ||:
          docker rm -f "$(docker ps -a -q)" ||:
          sudo rm -fr "$TEMP_PATH"
